  server:
    port: 8189
    servlet:
      context-path: /student
  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/studentsdb
      username: postgres
      password: postgres
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
      open-in-view: false